services:
  devcontainer:
    container_name: vsc-go-boilerplate
    build:
      context: ./.devcontainer
    working_dir: /workspace
    tty: true
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  # override: disable main app on development
  goapp: null
