services:
  devcontainer:
    container_name: vsc-go-boilerplate
    build:
      context: ./.devcontainer
    tty: true
    working_dir: /workspaces
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/..:/workspaces:cached
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  # override: disable main app on development
  goapp: null
